# Generated by Django 3.2.5 on 2021-07-15 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_auto_20210714_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category'},
        ),
        migrations.RemoveField(
            model_name='advert',
            name='category',
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sell.category'),
            preserve_default=False,
        ),
    ]
