# Generated by Django 3.2.5 on 2021-07-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_auto_20210715_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='advert',
            field=models.ManyToManyField(related_name='adverts', to='sell.Advert'),
        ),
    ]
