# Generated by Django 3.2.5 on 2021-07-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_category_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='advert',
        ),
    ]
