# Generated by Django 3.2.3 on 2021-07-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_category_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='advert',
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
